import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    scrollView: {
        flex: 1,
        width: '100%',
    },
    nav: {
        width: '100%',
        height: 160,
        borderBottomColor: '#007099',
        borderBottomWidth: 2,
    },
    topNav:{
        height: '100%',
        display: 'flex',
        flexDirection: 'row',
    },
    logoNav:{
        height: '100%',
        width: '75%',
        display: 'flex',
        flexDirection: 'row',
        justifyContent:"flex-start",
        alignItems: 'center',
        paddingLeft: '8%'
    },
    iconImg:{
        width: 75,
        height: 75,
    },
    logoImg:{
        width: 132,
        height: 40,
    },
    confNav:{
        width: '25%',
        height: '100%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
    },
    nameUser:{
        fontSize: 25,
        marginLeft: 20
    },
    territorios: {
        width: '100%',
        marginTop: 20,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
    },
    presable:{
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
    },
    iconAnimalImg:{
        width: 75,
        height: 75,
        borderRadius: 20,
    },

    territorioAzul:{
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        width: '80%',
        height: 100,
        borderWidth: 2,
        borderRadius: 10, 
        borderColor: 'rgba(0, 138,185, 1)',
        marginBottom: 30,
    },
    territorioVermelho:{
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        width: '80%',
        height: 100,
        borderWidth: 2,
        borderRadius: 10, 
        borderColor: 'rgba(232, 2, 5, 1)',
        marginBottom: 30,
    },
    territorioVerde:{
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        width: '80%',
        height: 100,
        borderWidth: 2,
        borderRadius: 10, 
        borderColor: 'rgba(82, 164, 4, 1)',
        marginBottom: 30,
    },
    territorioRoxo:{
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        width: '80%',
        height: 100,
        borderWidth: 2,
        borderRadius: 10, 
        borderColor: 'rgba(98, 37, 141, 1)',
        marginBottom: 30,
    },
    territorioMarrom:{
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        width: '80%',
        height: 100,
        borderWidth: 2,
        borderRadius: 10, 
        borderColor: 'rgba(49, 22, 3, 1)',
        marginBottom: 30,
    },
    territorioRosa:{
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        width: '80%',
        height: 100,
        borderWidth: 2,
        borderRadius: 10, 
        borderColor: 'rgba(253, 186, 204, 1)',
        marginBottom: 30,
    },
    areaDino:{
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        width: '80%',
        height: 100,
        borderWidth: 2,
        borderRadius: 10, 
        borderColor: 'rgba(138, 118, 93, 1)',
        marginBottom: 30,
    },
    iconTerritorio:{
        width: '40%',
        height: '100%',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },
    titleTeritorio:{
        width: '60%',
        height: '100%',
        display: 'flex',
        justifyContent: 'center',
    },
    titleTeritorioR:{
        width: '60%',
        height: '100%',
        display: 'flex',
        alignItems: 'flex-end',
        justifyContent: 'center',
    },
    nameTerritorio:{
        fontSize: 23,
    },
    configImg:{
        width: 30,
        height: 30, 
    }

});

export default styles;
